### ISSUE TITLE
In julia-0.5.0-dev+2591 the .* operator on DataArray{Float64,1} produces NA's

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataArrays.jl#179] opened 2016-02-11 19:24 UTC
I haven't diagnosed this in detail yet but

``` julia
julia> tt = DataArray([1.,2,3])
3-element DataArrays.DataArray{Float64,1}:
 1.0
 2.0
 3.0

julia> tt .^ 2
3-element DataArrays.DataArray{Float64,1}:
 1.0
 4.0
 9.0

julia> abs2(tt)
3-element DataArrays.DataArray{Float64,1}:
 1.0
 4.0
 9.0

julia> tt .* tt
3-element DataArrays.DataArray{Float64,1}:
 NA
 NA
 NA

julia> versioninfo()
Julia Version 0.5.0-dev+2591
Commit 2fbfd0e* (2016-02-11 05:27 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

julia> Pkg.status("DataArrays")
 - DataArrays                    0.2.20

```

**Comment by ararslan** [comment] 2017-07-05 04:26
The package no longer supports 0.5 (much less 0.5 prerelease) and I'm unable to reproduce this on recent Julia with the most recent version of the package, so I'm going to go ahead and close this. Feel free to reopen if you run into it again.

**Closed by ararslan** 2017-07-05 04:26 UTC
